name: Cypress
on: [push]
jobs:
  cypress-run:
    runs-on: [ubuntu-latest]
    container:
      image: cypress/included:13.6.4
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - uses: cypress-io/github-action@v6
      - uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots
